spring.datasource.username=refply_db
spring.datasource.password=xK9#mP2$vl7@nL4!!!bR3&wJ6
spring.datasource.url=jdbc:postgresql://localhost:5432/refply_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.default_schema=refply_schema
jwt.secretkey=t5S:L]^eH)4Uzn5Hi1szJJCB428?R%S!OZ:k?D,-TtWf@.=>iq4GTU0GXVR}S|X_uzwi&YD@Mw*2hTg3)JRz+
